### ISSUE TITLE
Theme/Style Gatsby Frontend

### ISSUE THREAD

**Issue by dtoki** [last-train/website#4]
### Restyle gatsby site to fit the last train.

~@tiakindele can you take this on and flesh out the issue a bit more?~

- [x] colour scheme
- [x] updates hosts
- [x] Add new favicon
- [x] update footer social links
- [x] hide the newletter
- [x] change polish to english on the frontend
- [x] update the fonts using brand guide
- [x] hide "downlod app section"

**Comment by dtoki** [comment]
@tiakindele break this down to smaller issues and assign some to me.
